// Menu structure
export interface Tenant {
  id: string; // The Unique Cafe ID
  name: string;
  location: string;
  currency: string; // e.g., "INR"
  taxRate: number; // e.g., 5 for 5% GST
}

export interface Category {
  id: string;
  tenantId: string;
  name: string; // e.g., "Hot Coffee", "Burgers"
  order: number; // For sorting in the UI
}

export interface InventoryItem {
  id: string;
  tenantId: string;
  name: string;
  unit: string;
  currentStock: number;
  minStock: number;
  threshold?: number;
}

export interface MenuItemRecipeIngredient {
  materialId: string;
  quantity: number;
}

export interface MenuItem {
  id: string;
  tenantId: string;
  categoryId: string;
  name: string;
  description?: string;
  price: number;
  image?: string;
  isAvailable: boolean;
  zomatoId?: string;
  swiggyId?: string;
  recipe?: MenuItemRecipeIngredient[];
}

export interface OrderItem {
  itemId: string;
  name: string;
  price: number;
  quantity: number;
  subtotal: number;
}

export interface Order {
  id: string; // Auto-generated by Firestore
  tenantId: string;
  orderNumber: number; // e.g., #101 (Daily sequence)
  items: OrderItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  status: "pending" | "completed" | "cancelled";
  paymentMethod: "cash" | "upi" | "card";
  createdAt: any; // Firestore Timestamp
  cashierId: string;
}
